(setq inhibit-splash-screen t)
(add-to-list 'load-path (expand-file-name "test" default-directory))
(add-to-list 'load-path (expand-file-name "emacs-source/lisp/emacs-lisp" default-directory))
(require 'eat)
(defun my-eat-exit (process)
  (kill-emacs))
(add-hook 'eat-exit-hook 'my-eat-exit)
(require 'compile)
(compile "echo warmup" t)
(setq eat-term-name "xterm-256color")
(let ((script (expand-file-name "test/perf.py" default-directory)))
  (eat (format "python3 %s" script)))
