(setq inhibit-splash-screen t)
(require 'compile)
(setq compilation-scroll-output t)
(require 'ansi-color)
(add-hook 'compilation-filter-hook 'ansi-color-compilation-filter)
(defun my-compilation-finish (buffer desc)
  (kill-emacs))
(add-hook 'compilation-finish-functions 'my-compilation-finish)
(compile "python3 test/perf.py" t)
