(setq inhibit-splash-screen t)
(require 'compile)
(require 'ansi-color)
(add-hook 'compilation-filter-hook 'ansi-color-compilation-filter)
(add-to-list 'load-path default-directory)
(require 'comint-9term)
(defun my-compilation-finish (buffer desc)
  (kill-emacs))
(add-hook 'compilation-finish-functions 'my-compilation-finish)
(add-hook 'compilation-mode-hook 'comint-9term-setup)
(compile "test/perf.py" t)
