(setq inhibit-splash-screen t)
(add-to-list 'load-path (expand-file-name "test" default-directory))
(require 'xterm-color)
(require 'comint)
(defun my-comint-finish (proc event)
  (when (string-match-p "finished" event)
    (kill-emacs)))
(let* ((buf (get-buffer-create "*perf-xterm*"))
       (script (expand-file-name "test/perf.py" default-directory))
       (proc (let ((process-environment (cons "TERM=xterm-256color" process-environment)))
               (start-file-process "perf" buf "python3" script))))
  (with-current-buffer buf
    (comint-mode)
    (setq-local comint-output-filter-functions (remove 'ansi-color-process-output comint-output-filter-functions))
    (add-hook 'comint-preoutput-filter-functions 'xterm-color-filter nil t)
    (set-process-filter proc 'comint-output-filter)
    (set-process-sentinel proc 'my-comint-finish)
    (pop-to-buffer buf)))
