(setq inhibit-splash-screen t)
(add-to-list 'load-path (expand-file-name "test" default-directory))
(add-to-list 'load-path (expand-file-name "emacs-source/lisp/emacs-lisp" default-directory))
(require 'eat)
(setq eat-term-name "xterm-256color")
(defun my-eat-exit (process)
  (with-current-buffer (process-buffer process)
    (write-region (point-min) (point-max) "eat-apt-output2.txt"))
  (kill-emacs))
(add-hook 'eat-exit-hook 'my-eat-exit)
(require 'compile)
(compile "echo warmup" t)
(let ((script (expand-file-name "test/perf-apt-prog.sh" default-directory)))
  (eat script))
